ci(centos): update lowest version of git
centos 6 [has officially reach end of
life](https://cloud.google.com/compute/docs/eol/centos6). Start using
centos 7 as are our base image for the oldest git version that is
supported. Update the `image:` to use centos:7 and install the missing
tools.

When we try to install git on a centos 6 machine the following error is
shown:
```
$ yum install -y -q git && git version
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. Invalid release/repo/arch combination/
```

closes https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27272