Update lsif-go container version to 1.9.0
Otherwise we get the following error:

    error: failed to list modules: exit status 1
    go: updates to go.sum needed, disabled by -mod=readonly