Fix Docker Windows tests
Create a new method `getBuildForOS` which will get the correct image and
executor for Windows so we don't see errors like:

```
Error:      	"executor requires OSType=linux, but Docker Engine supports only OSType=windows"
```

Not all of the tests are fixed becuase they required more changes, the
main goal of this commit is to fix the ones that require the default
build returned from `getBuildForOS` the other tests should be fixed in
follow up commits.

Tests not fixed:
- TestDockerCommandOutput
- TestDockerCommandTwoServicesFromOneImage
- TestDockerCommandWithAllowedImagesRun
- TestDockerCommandUsingCustomClonePath
- TestDockerImageNameFromVariable
- TestCacheInContainer
- TestDockerExtendedConfigurationFromJob
- TestDockerPrivilegedServiceAccessingBuildsFolder
- TestDockerCommandTwoServicesFromOneImage